version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shredhub
    env_file:
      - .env
    ports:
      - "${SHREDHUB_PORT}:8000"
    volumes:
      - ./app:/app
      - ./migrations:/migrations
      - ./logs:/logs
    environment:
      DOCKER_ENV: dev
    restart: always
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    # command:
    #   - postgres -p 5432
volumes:
  postgres-data: